services:
  api_hermes:
    volumes:
      - ./config.yaml.example:/config.yaml
    container_name: api_hermes
    build: .
    environment:
      - CONFIG_PATH=/config.yaml
      - DEF_ROUTER_IP_VLAN={"101":"137.194.8.1","102":"195.14.28.1"}
      - FILE_SAVING_PATH=/dev/shm
    ports:
      - "80:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api_hermes:8000/"]
      interval: 20s
      timeout: 10s
      retries: 5




 
