services:
  api_hermes:
    volumes:
      - ./tests/unit_tests_config.yaml.example:/config.yaml
    container_name: api_hermes
    build: .
    environment:
      - CONFIG_PATH=/config.yaml
      - TOKEN_NETBOX=91a0e80dd5c290ba0d7f7d070a9f3fd80a61e6ea
      - URL_NETBOX=http://netbox.dev.fai.rezel.net/graphql/
      - DEF_ROUTER_IP_VLAN={"101":"137.194.8.1","102":"195.14.28.1"}
      - FILE_SAVING_PATH=/dev/shm
    ports:
      - "80:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api_hermes:8000/status"]
      interval: 20s
      timeout: 10s
      retries: 5

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"

  mongodb-import:
    container_name: mongodb-import
    image: mongodb/mongodb-community-server:latest
    links:
      - mongodb
    volumes:
      - ./tests/mongodb-import:/mongodb-import
    command:
      /mongodb-import/import.sh
    

  unit_tests:
    container_name: unit_tests
    depends_on:
       api_hermes:
          condition: service_healthy
    build: 
      context: ./tests/
      dockerfile: Dockerfile.unit_tests
    environment:
      - PATH_DEFAULT_CONFIG_FILE=/
      - NAME_DEFAULT_CONFIG_FILE=test_ac2350_defaultConfigfile.txt

      - PATH_DEFAULT_CONFIG_FILE_TEST=/
      - NAME_DEFAULT_CONFIG_FILE_TEST=test_ac2350_defaultConfigfileTest_received.txt

      - MAC=00:00:00:00:00:00
      - PATH_CONFIG_FILE=/
      - NAME_CONFIG_FILE=test_ac2350_configfile.txt

      - PATH_CONFIG_FILE_TEST=/
      - NAME_CONFIG_FILE_TEST=test_ac2350_configfile_received.txt

      - URL=http://api_hermes:8000
      - ENDPOINT_DEFAULT_CONFIG=/v1/config/ac2350/default/file
      - ENDPOINT_CONFIG=/v1/config/ac2350/
      - ENDPOINT_STATUS=/status
    


 
