services:
  api_hermes:
    volumes:
      - ./config.yaml:/config.yaml
    container_name: api_hermes
    build: .
    environment:
      - CONFIG_PATH=/config.yaml
      - FILE_SAVING_PATH=/dev/shm
      - PTAH_ACCESS_TOKEN=$PTAH_ACCESS_TOKEN
    ports:
      - "80:8000"
