services:
  api_hermes:
    volumes:
      - ./config.yaml.example:/config.yaml
    container_name: api_hermes
    build: .
    environment:
      - CONFIG_PATH=/config.yaml
      - TOKEN_NETBOX=91a0e80dd5c290ba0d7f7d070a9f3fd80a61e6ea
      - URL_NETBOX=http://netbox.dev.fai.rezel.net/graphql/
      - DEF_ROUTER_IP_VLAN={"101":"137.194.8.1","102":"195.14.28.1"}
      - FILE_SAVING_PATH=/dev/shm
    ports:
      - "80:8000"
    networks:
        app_net:
            ipv6_address: fe80::5

# commande to ping : ping6 fe80::5%eth0
  test_ipv6:
    container_name: test_ipv6
    build: ./test_ipv6
    networks:
        app_net:
            ipv6_address: fe80::4

networks:
  app_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "fe80::/64"