services:
  api_hermes:
    # volumes:
    #   - ./requirements.txt:/hermes/requirements.txt
    container_name: api_hermes
    build: .
    ports:
      - "443:443"
      - "80:80"
      - "8000:8000"
