services:
  api_hermes:
    container_name: api_hermes
    command: --reload
    build: ..
    env_file:
      - .env.local
      - .env.secrets
    ports:
      - "8000:8000"
    network_mode: host
    volumes:
      - ../hermes:/hermes:Z


  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"

  mongodb-import:
    container_name: mongodb-import
    image: mongodb/mongodb-community-server:latest
    links:
      - mongodb
    volumes:
      - ./mongodb-import:/mongodb-import:Z
    command: >
      bash -c '
      mongoimport --host mongodb --db test --collection boxes --type json --file /mongodb-import/test.boxes.json --jsonArray'
