# Use a base image
FROM alpine:latest


# Install necessary dependencies
RUN apk update && apk add --no-cache bash curl jq dos2unix

# Copy the script to the container
COPY unit_tests.sh .

COPY test_ac2350_defaultConfigfile.txt .
COPY test_ac2350_configfile.txt .

# Make the script executable
RUN chmod +x unit_tests.sh
# Because some bad guys code on Windows with CRLF
RUN dos2unix unit_tests.sh
RUN dos2unix test_ac2350_defaultConfigfile.txt
RUN dos2unix test_ac2350_configfile.txt

USER nonroot

# Run the script when the container starts
CMD ["./unit_tests.sh"]
# CMD ["sleep", "infinity"]