apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-deployment
  namespace: ${DEPLOY_NAMESPACE}
  labels:
    app: hermes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes
  template:
    metadata:
      labels:
        app: hermes
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "hermes_${DEPLOY_ENV}"
        vault.hashicorp.com/agent-inject-template-env: | # Writes at /vault/secrets/env
          {{ with secret "kv/data/hermes_${DEPLOY_ENV}" -}}
            MONGODB_PASSWORD="{{ .Data.data.mongodb_password }}"
          {{- end }}
    spec:
      serviceAccountName: hermes-ksa
      containers:
      - name: hermes-container
        image: $IMAGE_TAG
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        args:
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "8000"
        env:
        - name: DEPLOY_ENV
          value: "${DEPLOY_ENV}"
        - name: VAULT_URL
          value: "https://vault.core.rezel.net"
        - name: VAULT_ROLE_NAME
          value: "hermes_${DEPLOY_ENV}"
      imagePullSecrets:
       - name: gitlab-registery-credentials
