apiVersion: v1
kind: Service
metadata:
  name: hermes
  namespace: default
  annotations:
    kube-vip.io/loadbalancerIPs: 137.194.15.36
spec:
  type: LoadBalancer
  selector:
    app: hermes
  loadBalancerClass: kube-vip.io/kube-vip-class
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: hermes
  namespace: dev
  annotations:
    kube-vip.io/loadbalancerIPs: 137.194.15.36
spec:
  type: LoadBalancer
  selector:
    app: hermes
  loadBalancerClass: kube-vip.io/kube-vip-class
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8000
