apiVersion: v1
kind: Service
metadata:
  name: hermes
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hermes
  loadBalancerClass: kube-vip.io/kube-vip-class
  externalIPs:
    - 137.194.15.36
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000