openapi: "3.0.0"
info:
  title: "Hermes API"
  description: "API to download files from Hermes to a box"
  version: "1.0.0"
servers:
  - url: "http://localhost:8000"
paths:
  /:
    get:
      summary: "Root path"
      description: "Root path of the API"
      responses:
        '200':
          description: "Root path"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"

  /v1/config/ac2350/{mac}:
    get:
      summary: "Download config file from Hermes to box"
      description: "Endpoint to download config file from Hermes to box based on MAC address"
      parameters:
        - name: "mac"
          in: "path"
          description: "MAC address of the box"
          required: true
          schema:
            type: "string"
      responses:
        '200':
          description: "File downloaded successfully"
          content:
            application/octet-stream:
              schema:
                type: "string"
                format: "binary"
        '500':
          description: "Internal server error"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  Erreur:
                    type: "string"
        '404':
          description: "Invalid MAC address"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  Erreur:
                    type: "string"
  /v1/config/ac2350/default/file:
    get:
      summary: "Download default config file from Hermes"
      description: "Endpoint to download default config file from Hermes"
      responses:
        '200':
          description: "File downloaded successfully"
          content:
            application/octet-stream:
              schema:
                type: "string"
                format: "binary"
        
       